debug: true
server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # none, create ...
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    output:
      ansi:
        enabled: always
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
service:
  base:
    url: ${BASE_URL}