debug: true
server:
  port: 3000
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # none, create ...
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    output:
      ansi:
        enabled: always
#    init:
#      platform: postgresql
#      mode: always
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
service:
  base:
    url: ${BASE_URL}