name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup jdk-17
      uses: actions/setup-java@v3
      with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
    - name: Build with Maven
      run: mvn clean package
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_package
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDS }}
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: java-app
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: kino-backend
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '*.jar'