name: Build and deploy JAR to GCP

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

env:
  IMAGE_URL: europe-west4-docker.pkg.dev/kino-backend-00001-4qc}/kino-back-repo}/kino-backend:${{ github.sha }}

# replace region with your region, ex: europe-north1-docker.pkg.dev
# also replace all project-id etc to match your situation. 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '21'
      - name: Run tests
        run: mvn clean test 
        
      - name: Build jar
        if: success() 
        run: mvn package 

      - name: Docker Build
        run: docker build -t $IMAGE_URL .
      - name: Docker Push
        run: docker push $IMAGE_URL

      - name: Update Cloud Run service
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: kino-backend
          image: ${{ env.IMAGE_URL }}